# Autogenerated file, run BuildBoost.bat [path_to_boost] to generate 
BOOSTPATH=C:\sources\boost_1_49_0\boost_1_49_0 
BOOSTLIBPATH=C:\sources\boost_1_49_0\boost_1_49_0\bin.v2\libs\regex\build\msvc-9.0 
